---
title: "The MetaRbolomics book"
author: "Jan Stanstrup"
---


```{r setup, include=FALSE}
library("knitr")
format <- opts_knit$get('rmarkdown.pandoc.to')

if (format=="html") opts_chunk$set(dev = 'svg')
if (format=="pdf")  opts_chunk$set(dev = 'pdf')
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(readr)

# read package list
pack_list <- read_tsv("https://raw.githubusercontent.com/sneumann/metaRbolomics/master/connectivity/AllMetaRbolomicsTables.csv",
                      col_types=cols(
                                       Table = col_character(),
                                       Section = col_character(),
                                       Functionalities = col_character(),
                                       Package = col_character(),
                                       Code_link = col_character(),
                                       Repo = col_character()
                                     )
                     )

metaRbolomics_show_table <- function(table_text = "Table 1:"){
    require(DT)
    require(dplyr)
    
    caption <- pack_list$Table %>% 
                    unique() %>% 
                    grep(table_text, ., value = TRUE)
    
    pack_list %>% 
        filter(grepl(table_text, Table)) %>% 
        mutate(Package = paste0('<a target=_blank href=', Code_link, '>', Package,'</a>' )) %>% 
        select(-Table, -Code_link) %>% 
        
        datatable(pack_list, 
                      extensions = "RowGroup", 
                      options = list(rowGroup=list(dataSrc=0),
                                     ordering=FALSE,
                                     columnDefs = list(list(visible=FALSE, targets=c(0))), # hide rownames
                                     pageLength = -1, # show all entries
                                     dom = 'ft' # remove nagivation
                                     ),
                      rownames= FALSE, 
                      escape = FALSE,
                      fillContainer=FALSE,
                      caption = caption
                      )
}

```


# Introduction

<style>
.book .book-body .page-wrapper .page-inner {
max-width: 1200px !important;
}
</style>

# R-packages for metabolomics

<!--chapter:end:index.Rmd-->

---
title: "Second chap"
author: "Jan Stanstrup"
---





\pagebreak


## Mass spectrometry data handling and (pre-)processing

<style>
.book .book-body .page-wrapper .page-inner {
max-width: 1200px !important;
}
</style>

```{r, warning=FALSE, echo=FALSE, message=FALSE}
metaRbolomics_show_table("Table 1:")
```


```{r, warning=FALSE, echo=FALSE, message=FALSE}
metaRbolomics_show_table("Table 2:")
```


    
## Metabolite identification with MS/MS data

```{r, warning=FALSE, echo=FALSE, message=FALSE}
metaRbolomics_show_table("Table 3:")
```


<!--chapter:end:02-mass_spectrometry_data_handling_pre_processing.Rmd-->

